language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
before_script:
  - psql -c 'create database cinemateca_potiguar_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
script:
  - bundle exec rspec
